import { fontRoboto, fontRobotoMono } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";
import WalletProvider from "@/providers/wallet-provider";
import AppProvider from "@/providers/app-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen bg-background font-roboto antialiased",
					fontRoboto.variable,
					fontRobotoMono.variable,
				)}
			>
				<WalletProvider appName="Asset DID COM">{children}</WalletProvider>
			</body>
		</html>
	);
}
